#!/usr/bin/env python3
"""Build and analyze a timestamped YouTube channel research corpus."""

from __future__ import annotations

import argparse
import concurrent.futures
import datetime as dt
import html
import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Iterable


SKILL_DIR = Path(__file__).resolve().parent.parent
DEFAULT_SERVER = "http://127.0.0.1:4096"
DEFAULT_MODEL = {"providerID": "google", "modelID": "gemini-3.1-pro-preview"}
TIMING_RE = re.compile(
    r"^(?P<start>(?:\d{2}:)?\d{2}:\d{2}[.,]\d{3})\s+-->\s+"
    r"(?P<end>(?:\d{2}:)?\d{2}:\d{2}[.,]\d{3})"
)
TAG_RE = re.compile(r"<[^>]+>")
INLINE_TIME_RE = re.compile(r"<\d{2}:\d{2}:\d{2}[.,]\d{3}>")
STATE_LOCK = threading.Lock()


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat()


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    temp.write_text(content, encoding="utf-8")
    temp.replace(path)


def append_jsonl(path: Path, record: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(record, ensure_ascii=True) + "\n"
    with STATE_LOCK:
        with path.open("a", encoding="utf-8") as handle:
            handle.write(line)


def require_corpus(root: Path) -> dict[str, Any]:
    config_path = root / "project.json"
    if not config_path.exists():
        raise SystemExit(f"Not a corpus: {root}. Run the init command first.")
    return json.loads(config_path.read_text(encoding="utf-8"))


def cmd_init(args: argparse.Namespace) -> None:
    root = args.root.expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    for name in ("sources", "reports", "state"):
        (root / name).mkdir(exist_ok=True)

    project = {
        "schema_version": 1,
        "created_at": now_iso(),
        "model": DEFAULT_MODEL,
        "server": DEFAULT_SERVER,
    }
    if not (root / "project.json").exists():
        atomic_write(root / "project.json", json.dumps(project, indent=2) + "\n")
    if not (root / "channels.txt").exists():
        atomic_write(
            root / "channels.txt",
            "# One canonical channel tab URL per line.\n"
            "# https://www.youtube.com/@handle/videos\n"
            "# https://www.youtube.com/@handle/shorts\n"
            "# https://www.youtube.com/@handle/streams\n",
        )
    if not (root / "context.md").exists():
        atomic_write(
            root / "context.md",
            "# Research Context\n\n"
            "## Questions\n\n"
            "Describe what you need to learn or test.\n\n"
            "## Existing Context\n\n"
            "Add your notes, claims, documents, and assumptions here. Mark sources where known.\n\n"
            "## Terms And Entities\n\n"
            "List names or vocabulary that autogenerated captions may mistranscribe.\n",
        )
    print(root)


def executable_status(name: str) -> tuple[bool, str]:
    path = shutil.which(name)
    return (path is not None, path or "missing")


def http_json(
    url: str,
    *,
    method: str = "GET",
    payload: dict[str, Any] | None = None,
    timeout: int = 30,
) -> Any:
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        method=method,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        body = response.read()
        if not body:
            return None
        return json.loads(body.decode("utf-8"))


def server_healthy(server: str) -> bool:
    try:
        result = http_json(f"{server}/global/health", timeout=2)
        return bool(result and result.get("healthy"))
    except (OSError, urllib.error.URLError, json.JSONDecodeError):
        return False


def start_server(root: Path, server: str) -> None:
    if server_healthy(server):
        return
    match = re.fullmatch(r"http://([^:/]+):(\d+)", server)
    if not match:
        raise RuntimeError(f"Cannot auto-start non-local server URL: {server}")
    host, port = match.groups()
    log_path = root / "state" / "opencode-server.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_handle = log_path.open("ab")
    process = subprocess.Popen(
        ["opencode", "serve", "--hostname", host, "--port", port],
        stdin=subprocess.DEVNULL,
        stdout=log_handle,
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    atomic_write(root / "state" / "opencode-server.pid", f"{process.pid}\n")
    for _ in range(60):
        if server_healthy(server):
            return
        if process.poll() is not None:
            break
        time.sleep(0.5)
    raise RuntimeError(f"OpenCode server failed to start; inspect {log_path}")


def cmd_doctor(args: argparse.Namespace) -> None:
    failed = False
    for executable in ("yt-dlp", "ffmpeg", "node", "opencode"):
        ok, detail = executable_status(executable)
        print(f"{'OK' if ok else 'MISSING'}  {executable}: {detail}")
        failed = failed or not ok

    model_ok = False
    if shutil.which("opencode"):
        result = subprocess.run(
            ["opencode", "models", "google"],
            text=True,
            capture_output=True,
            check=False,
        )
        model_id = f"{DEFAULT_MODEL['providerID']}/{DEFAULT_MODEL['modelID']}"
        model_ok = model_id in result.stdout
        print(f"{'OK' if model_ok else 'MISSING'}  model: {model_id}")
    failed = failed or not model_ok
    print(f"{'OK' if server_healthy(args.server) else 'OFFLINE'}  server: {args.server}")
    if failed:
        raise SystemExit(1)


def read_channel_urls(root: Path, extras: Iterable[str]) -> list[str]:
    urls = list(extras)
    channel_file = root / "channels.txt"
    if channel_file.exists():
        for line in channel_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                urls.append(line)
    return list(dict.fromkeys(urls))


def clean_caption_text(lines: list[str]) -> str:
    text = " ".join(lines)
    text = INLINE_TIME_RE.sub("", text)
    text = TAG_RE.sub("", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def seconds_from_timestamp(value: str) -> int:
    parts = value.replace(",", ".").split(":")
    if len(parts) == 2:
        hours = 0
        minutes, seconds = parts
    else:
        hours, minutes, seconds = parts
    return int(hours) * 3600 + int(minutes) * 60 + int(float(seconds))


def display_timestamp(value: str) -> str:
    whole = seconds_from_timestamp(value)
    hours, remainder = divmod(whole, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}"
    return f"{minutes:02d}:{seconds:02d}"


def parse_vtt(path: Path, video_id: str) -> list[str]:
    raw_lines = path.read_text(encoding="utf-8-sig", errors="replace").splitlines()
    output: list[str] = []
    previous = ""
    index = 0
    while index < len(raw_lines):
        match = TIMING_RE.match(raw_lines[index].strip())
        if not match:
            index += 1
            continue
        start = match.group("start")
        index += 1
        cue_lines: list[str] = []
        while index < len(raw_lines) and raw_lines[index].strip():
            cue_lines.append(raw_lines[index].strip())
            index += 1
        text = clean_caption_text(cue_lines)
        if not text or text == previous or (previous and previous.startswith(text)):
            continue
        if previous and text.startswith(previous) and len(previous) >= 20:
            delta = text[len(previous) :].strip(" -")
            if delta:
                text = delta
            else:
                continue
        seconds = seconds_from_timestamp(start)
        url = f"https://www.youtube.com/watch?v={video_id}&t={seconds}s"
        output.append(f"[{display_timestamp(start)}]({url}) {text}")
        previous = clean_caption_text(cue_lines)
    return output


def safe_language(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._") or "unknown"


def metadata_summary(metadata: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "id",
        "title",
        "description",
        "channel",
        "channel_id",
        "uploader",
        "upload_date",
        "timestamp",
        "duration",
        "view_count",
        "like_count",
        "comment_count",
        "categories",
        "tags",
        "webpage_url",
    )
    return {key: metadata.get(key) for key in keys if metadata.get(key) is not None}


def normalize_video(info_path: Path) -> bool:
    try:
        metadata = json.loads(info_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        print(f"WARN invalid metadata {info_path}: {error}", file=sys.stderr)
        return False
    video_id = str(metadata.get("id") or info_path.name.split(".", 1)[0])
    vtt_files = sorted(info_path.parent.glob(f"{video_id}.*.vtt"))
    if not vtt_files:
        return False

    manual_languages = set((metadata.get("subtitles") or {}).keys())
    candidates: list[tuple[int, Path, str, str]] = []
    for vtt_path in vtt_files:
        prefix = f"{video_id}."
        language = vtt_path.name[len(prefix) : -len(".vtt")]
        caption_kind = "manual" if language in manual_languages else "automatic"
        preferred = 0 if language in {"en", "en-US", "en-GB"} else 1
        manual_rank = 0 if caption_kind == "manual" else 1
        candidates.append((preferred * 2 + manual_rank, vtt_path, language, caption_kind))

    candidates.sort(key=lambda item: (item[0], item[2]))
    selected: str | None = None
    transcript_dir = info_path.parent / "transcripts"
    transcript_dir.mkdir(exist_ok=True)
    for _, vtt_path, language, caption_kind in candidates:
        cues = parse_vtt(vtt_path, video_id)
        if not cues:
            continue
        title = str(metadata.get("title") or video_id).replace("\n", " ")
        source = metadata.get("webpage_url") or f"https://www.youtube.com/watch?v={video_id}"
        content = (
            f"# {title}\n\n"
            f"- Video ID: `{video_id}`\n"
            f"- Source: {source}\n"
            f"- Language: `{language}`\n"
            f"- Caption type: `{caption_kind}`\n\n"
            "## Transcript\n\n"
            + "\n\n".join(cues)
            + "\n"
        )
        output = transcript_dir / f"{safe_language(language)}.md"
        atomic_write(output, content)
        if selected is None:
            selected = content
    if selected is not None:
        atomic_write(info_path.parent / "transcript.md", selected)
        return True
    return False


def normalize_corpus(root: Path) -> tuple[int, int]:
    found = 0
    normalized = 0
    for info_path in sorted((root / "sources").glob("*/*/*.info.json")):
        found += 1
        normalized += int(normalize_video(info_path))
    return found, normalized


def cmd_ingest(args: argparse.Namespace) -> None:
    root = args.root.expanduser().resolve()
    require_corpus(root)
    urls = read_channel_urls(root, args.url)
    if not urls:
        raise SystemExit(f"No channel URLs found. Add them to {root / 'channels.txt'}")
    command = [
        "yt-dlp",
        "--ignore-errors",
        "--no-abort-on-error",
        "--skip-download",
        "--write-info-json",
        "--no-clean-info-json",
        "--write-description",
        "--write-thumbnail",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs",
        args.sub_langs,
        "--sub-format",
        "vtt",
        "--download-archive",
        str(root / "state" / "ingest.archive"),
        "--force-write-archive",
        "--sleep-requests",
        str(args.sleep_requests),
        "--sleep-subtitles",
        str(args.sleep_subtitles),
        "-P",
        str(root / "sources"),
        "-o",
        "%(channel_id,uploader_id,channel,uploader|unknown-channel)s/%(id)s/%(id)s.%(ext)s",
        *urls,
    ]
    print("Running yt-dlp metadata and caption ingestion...", flush=True)
    result = subprocess.run(command, check=False)
    found, normalized = normalize_corpus(root)
    print(f"Metadata records: {found}; normalized transcripts: {normalized}")
    if result.returncode not in (0, 1):
        raise SystemExit(result.returncode)


def load_prompt(name: str) -> str:
    return (SKILL_DIR / "references" / name).read_text(encoding="utf-8")


def model_call(
    server: str,
    model: dict[str, str],
    title: str,
    prompt: str,
    timeout: int,
) -> str:
    session = http_json(
        f"{server}/session",
        method="POST",
        payload={"title": title},
        timeout=30,
    )
    session_id = session["id"]
    try:
        response = http_json(
            f"{server}/session/{session_id}/message",
            method="POST",
            payload={
                "model": model,
                "variant": "high",
                "parts": [{"type": "text", "text": prompt}],
            },
            timeout=timeout,
        )
        text_parts = [
            part.get("text", "")
            for part in response.get("parts", [])
            if part.get("type") == "text"
        ]
        output = "\n".join(part for part in text_parts if part).strip()
        if not output:
            raise RuntimeError("OpenCode returned no text output")
        return output + "\n"
    finally:
        try:
            http_json(f"{server}/session/{session_id}", method="DELETE", timeout=30)
        except Exception as error:  # Cleanup must not hide the model result.
            print(f"WARN failed to delete OpenCode session {session_id}: {error}", file=sys.stderr)


def video_records(root: Path) -> list[tuple[Path, Path, Path]]:
    records = []
    for transcript in sorted((root / "sources").glob("*/*/transcript.md")):
        info_files = sorted(transcript.parent.glob("*.info.json"))
        if info_files:
            records.append((transcript.parent, transcript, info_files[0]))
    return records


def cmd_analyze_video(args: argparse.Namespace) -> None:
    root = args.root.expanduser().resolve()
    config = require_corpus(root)
    server = args.server or config.get("server", DEFAULT_SERVER)
    model = config.get("model", DEFAULT_MODEL)
    start_server(root, server)
    context = (root / "context.md").read_text(encoding="utf-8")
    base_prompt = load_prompt("video-analysis-prompt.md")
    records = video_records(root)
    if args.video_id:
        wanted = set(args.video_id)
        records = [record for record in records if record[0].name in wanted]
    records = [
        record
        for record in records
        if args.force or not (record[0] / "analysis.md").exists()
    ]
    print(f"Pending video analyses: {len(records)}", flush=True)

    def analyze(record: tuple[Path, Path, Path]) -> tuple[str, bool, str]:
        video_dir, transcript_path, info_path = record
        video_id = video_dir.name
        started = now_iso()
        try:
            metadata = json.loads(info_path.read_text(encoding="utf-8"))
            prompt = (
                base_prompt
                + "\n\n<metadata>\n"
                + json.dumps(metadata_summary(metadata), ensure_ascii=False, indent=2)
                + "\n</metadata>\n\n<user_context>\n"
                + context
                + "\n</user_context>\n\n<transcript>\n"
                + transcript_path.read_text(encoding="utf-8")
                + "\n</transcript>\n"
            )
            output = model_call(server, model, f"YouTube analysis: {video_id}", prompt, args.timeout)
            header = (
                f"<!-- model: {model['providerID']}/{model['modelID']} -->\n"
                f"<!-- analyzed_at: {now_iso()} -->\n\n"
            )
            atomic_write(video_dir / "analysis.md", header + output)
            record_state = {
                "video_id": video_id,
                "status": "done",
                "started_at": started,
                "finished_at": now_iso(),
                "model": model,
            }
            append_jsonl(root / "state" / "analysis.jsonl", record_state)
            return video_id, True, "done"
        except Exception as error:
            append_jsonl(
                root / "state" / "analysis.jsonl",
                {
                    "video_id": video_id,
                    "status": "failed",
                    "started_at": started,
                    "finished_at": now_iso(),
                    "error": str(error),
                    "model": model,
                },
            )
            return video_id, False, str(error)

    failures = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency) as executor:
        futures = [executor.submit(analyze, record) for record in records]
        for future in concurrent.futures.as_completed(futures):
            video_id, ok, detail = future.result()
            print(f"{'DONE' if ok else 'FAIL'} {video_id}: {detail}", flush=True)
            failures += int(not ok)
    if failures:
        raise SystemExit(1)


def pack_documents(documents: list[tuple[str, str]], max_chars: int) -> list[list[tuple[str, str]]]:
    batches: list[list[tuple[str, str]]] = []
    current: list[tuple[str, str]] = []
    current_size = 0
    for name, content in documents:
        item_size = len(name) + len(content)
        if current and current_size + item_size > max_chars:
            batches.append(current)
            current = []
            current_size = 0
        current.append((name, content))
        current_size += item_size
    if current:
        batches.append(current)
    return batches


def render_documents(documents: list[tuple[str, str]]) -> str:
    return "\n\n".join(
        f"<document name={json.dumps(name)}>\n{content}\n</document>"
        for name, content in documents
    )


def synthesize_documents(
    server: str,
    model: dict[str, str],
    title: str,
    base_prompt: str,
    context: str,
    documents: list[tuple[str, str]],
    timeout: int,
    max_chars: int,
) -> str:
    batches = pack_documents(documents, max_chars)
    intermediate: list[tuple[str, str]] = []
    for index, batch in enumerate(batches, start=1):
        prompt = (
            base_prompt
            + "\n\nThis is an intermediate evidence batch. Preserve all source citations needed by final synthesis."
            + "\n\n<user_context>\n"
            + context
            + "\n</user_context>\n\n<analyses>\n"
            + render_documents(batch)
            + "\n</analyses>\n"
        )
        output = model_call(server, model, f"{title} batch {index}", prompt, timeout)
        intermediate.append((f"batch-{index}", output))
    if len(intermediate) == 1:
        return intermediate[0][1]
    final_prompt = (
        base_prompt
        + "\n\nCombine these intermediate evidence-preserving syntheses. Do not drop provenance."
        + "\n\n<user_context>\n"
        + context
        + "\n</user_context>\n\n<batch_syntheses>\n"
        + render_documents(intermediate)
        + "\n</batch_syntheses>\n"
    )
    return model_call(server, model, f"{title} final", final_prompt, timeout)


def cmd_synthesize(args: argparse.Namespace) -> None:
    root = args.root.expanduser().resolve()
    config = require_corpus(root)
    server = args.server or config.get("server", DEFAULT_SERVER)
    model = config.get("model", DEFAULT_MODEL)
    start_server(root, server)
    context = (root / "context.md").read_text(encoding="utf-8")
    base_prompt = load_prompt("synthesis-prompt.md")
    channels: dict[str, list[tuple[str, str]]] = {}
    for analysis_path in sorted((root / "sources").glob("*/*/analysis.md")):
        channel = analysis_path.parent.parent.name
        video_id = analysis_path.parent.name
        channels.setdefault(channel, []).append(
            (video_id, analysis_path.read_text(encoding="utf-8"))
        )
    if not channels:
        raise SystemExit("No per-video analyses found. Run analyze-video first.")

    channel_reports: list[tuple[str, str]] = []
    for channel, documents in sorted(channels.items()):
        print(f"Synthesizing {channel}: {len(documents)} video analyses", flush=True)
        output = synthesize_documents(
            server,
            model,
            f"Channel synthesis: {channel}",
            base_prompt,
            context,
            documents,
            args.timeout,
            args.max_chars,
        )
        header = (
            f"<!-- model: {model['providerID']}/{model['modelID']} -->\n"
            f"<!-- synthesized_at: {now_iso()} -->\n\n"
        )
        atomic_write(root / "reports" / f"{safe_language(channel)}.md", header + output)
        channel_reports.append((channel, output))

    cross_prompt = (
        base_prompt
        + "\n\nCross-analyze the channel reports against the supplied user context. "
        "Highlight agreement, conflict, missing evidence, and questions worth external verification."
        + "\n\n<user_context>\n"
        + context
        + "\n</user_context>\n\n<channel_reports>\n"
        + render_documents(channel_reports)
        + "\n</channel_reports>\n"
    )
    cross = model_call(server, model, "Cross-channel context analysis", cross_prompt, args.timeout)
    atomic_write(root / "reports" / "cross-analysis.md", cross)
    print(root / "reports" / "cross-analysis.md")


def cmd_status(args: argparse.Namespace) -> None:
    root = args.root.expanduser().resolve()
    config = require_corpus(root)
    metadata = list((root / "sources").glob("*/*/*.info.json"))
    transcripts = list((root / "sources").glob("*/*/transcript.md"))
    analyses = list((root / "sources").glob("*/*/analysis.md"))
    missing = sorted(
        str(path.parent.relative_to(root / "sources"))
        for path in metadata
        if not (path.parent / "transcript.md").exists()
    )
    print(f"Corpus: {root}")
    print(f"Model: {config['model']['providerID']}/{config['model']['modelID']}")
    print(f"Metadata records: {len(metadata)}")
    print(f"Normalized transcripts: {len(transcripts)}")
    print(f"Completed analyses: {len(analyses)}")
    print(f"Missing transcripts: {len(missing)}")
    for item in missing[:20]:
        print(f"  - {item}")
    if len(missing) > 20:
        print(f"  ... and {len(missing) - 20} more")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    doctor = subparsers.add_parser("doctor", help="Check local tools, model, and server")
    doctor.add_argument("--server", default=DEFAULT_SERVER)
    doctor.set_defaults(func=cmd_doctor)

    init = subparsers.add_parser("init", help="Create a research corpus")
    init.add_argument("root", type=Path)
    init.set_defaults(func=cmd_init)

    ingest = subparsers.add_parser("ingest", help="Fetch metadata and captions")
    ingest.add_argument("root", type=Path)
    ingest.add_argument("--url", action="append", default=[])
    ingest.add_argument("--sub-langs", default="all,-live_chat")
    ingest.add_argument("--sleep-requests", type=float, default=0.75)
    ingest.add_argument("--sleep-subtitles", type=float, default=2.0)
    ingest.set_defaults(func=cmd_ingest)

    analyze = subparsers.add_parser("analyze-video", help="Analyze normalized transcripts")
    analyze.add_argument("root", type=Path)
    analyze.add_argument("--video-id", action="append", default=[])
    analyze.add_argument("--concurrency", type=int, default=2)
    analyze.add_argument("--timeout", type=int, default=1200)
    analyze.add_argument("--server")
    analyze.add_argument("--force", action="store_true")
    analyze.set_defaults(func=cmd_analyze_video)

    synthesize = subparsers.add_parser("synthesize", help="Build channel and cross-context reports")
    synthesize.add_argument("root", type=Path)
    synthesize.add_argument("--timeout", type=int, default=1200)
    synthesize.add_argument("--max-chars", type=int, default=500_000)
    synthesize.add_argument("--server")
    synthesize.set_defaults(func=cmd_synthesize)

    status = subparsers.add_parser("status", help="Show corpus coverage")
    status.add_argument("root", type=Path)
    status.set_defaults(func=cmd_status)
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
