# Terminal emulator configuration: Alacritty, Kitty, Ghostty.
#
# All three `import`/`include` an omarchy theme file
# (~/.config/omarchy/current/theme/*.{toml,conf}) that is generated by the
# omanix module -- not part of this repo.
{ config, pkgs, lib, ... }:

{
  xdg.configFile = {
    "alacritty/alacritty.toml".source = ../files/alacritty/alacritty.toml;
    "kitty/kitty.conf".source = ../files/kitty/kitty.conf;
    "ghostty/config".source = ../files/ghostty/config;
  };
}
