# *** EXAMPLE ONLY -- THIS IS THE SOURCE MACHINE'S EXACT HARDWARE ***
# This file encodes THIS MACHINE's disk layout, LUKS device UUIDs, boot
# partition UUID, and swap device. It WILL NOT WORK on different hardware
# and will likely fail to boot or fail to decrypt disks if used as-is.
#
# Before using this repo on your own machine:
#   1. Install NixOS normally on your own disk.
#   2. Run `sudo nixos-generate-config` on your machine.
#   3. Replace this entire file with the one it generates at
#      /etc/nixos/hardware-configuration.nix.
#
# See the repo README for the full step-by-step.
#
# --- Original generated header follows ---
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1f8ba60f-0725-4a15-8c91-f894c75ec492";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1f8ba60f-0725-4a15-8c91-f894c75ec492".device = "/dev/disk/by-uuid/1f8ba60f-0725-4a15-8c91-f894c75ec492";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4A5E-6843";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f749c155-3d4e-4bfb-b6f6-cc0447b1f2f8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
