{
  "$schema": "https://opencode.ai/theme.json",
  "defs": {
    "bg": "{{ background }}",
    "bgPanel": "#0c1225",
    "bgElement": "#151b32",
    "fg": "{{ foreground }}",
    "fgMuted": "{{ color8 }}",
    "fgSubtle": "#81858b",
    "accent": "{{ accent }}",
    "accentBright": "{{ color12 }}",
    "red": "{{ color1 }}",
    "redBright": "{{ color9 }}",
    "green": "{{ color2 }}",
    "greenBright": "{{ color10 }}",
    "yellow": "{{ color3 }}",
    "yellowBright": "{{ color11 }}",
    "blue": "{{ color4 }}",
    "cyan": "{{ color6 }}",
    "cyanBright": "{{ color14 }}",
    "magenta": "{{ color5 }}",
    "magentaBright": "{{ color13 }}",
    "orange": "{{ color7 }}",
    "border": "{{ foreground }}22",
    "borderActive": "{{ accent }}",
    "borderSubtle": "{{ foreground }}14",
    "diffAddedBg": "#1a2a25",
    "diffRemovedBg": "#2b1828"
  },
  "theme": {
    "primary": "accent",
    "secondary": "cyan",
    "accent": "magenta",
    "error": "red",
    "warning": "yellow",
    "success": "green",
    "info": "accent",
    "text": "fg",
    "textMuted": "fgMuted",
    "background": "bg",
    "backgroundPanel": "bgPanel",
    "backgroundElement": "bgElement",
    "border": "border",
    "borderActive": "borderActive",
    "borderSubtle": "borderSubtle",
    "diffAdded": "green",
    "diffRemoved": "red",
    "diffContext": "fgMuted",
    "diffHunkHeader": "fgMuted",
    "diffHighlightAdded": "greenBright",
    "diffHighlightRemoved": "redBright",
    "diffAddedBg": "diffAddedBg",
    "diffRemovedBg": "diffRemovedBg",
    "diffContextBg": "bgPanel",
    "diffLineNumber": "fgMuted",
    "diffAddedLineNumberBg": "diffAddedBg",
    "diffRemovedLineNumberBg": "diffRemovedBg",
    "markdownText": "fg",
    "markdownHeading": "accent",
    "markdownLink": "blue",
    "markdownLinkText": "cyan",
    "markdownCode": "green",
    "markdownBlockQuote": "fgMuted",
    "markdownEmph": "orange",
    "markdownStrong": "yellow",
    "markdownHorizontalRule": "fgMuted",
    "markdownListItem": "accent",
    "markdownListEnumeration": "cyan",
    "markdownImage": "blue",
    "markdownImageText": "cyan",
    "markdownCodeBlock": "fg",
    "syntaxComment": "fgMuted",
    "syntaxKeyword": "magenta",
    "syntaxFunction": "accent",
    "syntaxVariable": "fg",
    "syntaxString": "green",
    "syntaxNumber": "yellow",
    "syntaxType": "cyan",
    "syntaxOperator": "cyanBright",
    "syntaxPunctuation": "fgSubtle"
  }
}
